# Configuration for TCN Forecasting Demo

batch_size: 64
learning_rate: 0.001
num_epochs: 30
print_every: 5
seq_len: 50
n_train: 1000
n_test: 600
noise_std: 0.1
anomaly_interval: 100
anomaly_magnitude: 3.0

# TCN parameters
num_channels: [32, 32, 32]  # List of output channels for each TCN block
kernel_size: 3
dropout: 0.2

device: "cuda"
output_dir: "outputs"
