# Configuration for LSTM Forecasting Demo

batch_size: 64
learning_rate: 0.001
num_epochs: 30
print_every: 5
seq_len: 50
n_train: 1000       # Number of data points for training
n_test: 600         # Number of data points for testing
noise_std: 0.1
anomaly_interval: 100  # Inject anomaly every 100 points in test series (starting mid-test)
anomaly_magnitude: 3.0

# LSTM model parameters
hidden_size: 64
num_layers: 1

device: "cuda"      # Use "cpu" if GPU is not available
output_dir: "outputs"
