# Configuration for Autoencoder Demo

# Training hyperparameters
batch_size: 128
learning_rate: 0.001
num_epochs: 10
latent_dim: 32

# Device settings: "cuda" or "cpu"
device: "cuda"

# Output directory for plots and results
output_dir: "outputs"
