# Configuration for Variational Autoencoder Demo

batch_size: 128
learning_rate: 0.001
num_epochs: 10
latent_dim: 20

# Device setting: "cuda" or "cpu"
device: "cuda"

# Output directory for plots and results
output_dir: "outputs"
