# Configuration for Ensemble Hybrid Anomaly Detection Demo (Ensemble Demo)

batch_size: 64
learning_rate: 0.001
num_epochs: 30
print_every: 5
seq_len: 50
n_train: 1000
n_test: 600
noise_std: 0.1
anomaly_interval: 100
anomaly_magnitude: 3.0

# LSTM model parameters
lstm_hidden: 64
lstm_layers: 1

# Ensemble weight: weight for autoencoder error (between 0 and 1)
alpha: 0.5

device: "cuda"   # Use "cpu" if no GPU available
output_dir: "outputs"
